import Footer from "@/layout/Footer";
import Header from "@/layout/Header";
import "@/style/style.scss";
import { Inter } from "next/font/google";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "M1 Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${InterFont.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
